-- STARBLAST advanced admin-center security + audit writer
-- Run this AFTER the earlier Starblast migrations. Safe to run repeatedly.

begin;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_username text not null,
  action text not null,
  target_user_id uuid null references auth.users(id) on delete set null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_logs enable row level security;
revoke all on table public.admin_audit_logs from anon, authenticated;
grant usage on schema public to service_role;
grant select, insert, update, delete on table public.admin_audit_logs to service_role;
grant usage, select on all sequences in schema public to service_role;

create or replace function public.write_admin_audit_log(
  p_admin_username text,
  p_action text,
  p_target_user_id uuid default null,
  p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare v_id bigint;
begin
  if trim(coalesce(p_admin_username,'')) = '' then raise exception 'admin username required'; end if;
  if trim(coalesce(p_action,'')) = '' then raise exception 'audit action required'; end if;
  insert into public.admin_audit_logs(admin_username,action,target_user_id,details)
  values(left(trim(p_admin_username),100),left(trim(p_action),100),p_target_user_id,coalesce(p_details,'{}'::jsonb))
  returning id into v_id;
  return v_id;
end;
$$;

revoke all on function public.write_admin_audit_log(text,text,uuid,jsonb) from public, anon, authenticated;
grant execute on function public.write_admin_audit_log(text,text,uuid,jsonb) to service_role;

create index if not exists admin_audit_created_idx on public.admin_audit_logs(created_at desc);
create index if not exists admin_audit_target_idx on public.admin_audit_logs(target_user_id,created_at desc);

commit;
